export const seoConfig = {
    title: "AK Events Deli - Premium Event Rentals in Kasaragod | Firoz Padinhar",
    description: "AK Events Deli by Firoz Padinhar - Leading event management company in Kasaragod, Kerala. Premium furniture rentals, sound systems by Shalimar Sounds. Luxury wedding & ceremony rentals in Melparamba.",
    keywords: [
      "AK Events Deli",
      "Firoz Padinhar",
      "Melparamba events",
      "Shalimar Sounds",
      "Shalimar Events", 
      "Kasaragod event management",
      "Kerala event rentals",
      "luxury furniture rental Kasaragod",
      "wedding planners Kerala",
      "event management Kerala",
      "premium event rentals",
      "fancy furniture rental",
      "buffet counter rental",
      "cooling fan rental",
      "event decorations Kasaragod",
      "marriage hall decorations",
      "ear piercing ceremony arrangements",
      "corporate events Kerala",
      "birthday party decorations",
      "sound system rental Kasaragod",
      "professional DJ services",
      "event photography Kerala",
      "wedding decorators Kasaragod",
      "party organizers Kerala",
      "luxury event planning",
      "premium wedding rentals",
      "event management services",
      "celebration planners Kerala",
      "festive decorations",
      "traditional ceremony arrangements"
    ],
    author: "AK Events Deli - Firoz Padinhar",
    siteUrl: "https://www.akevents-deli.com",
    image: "/images/ak-events-hero.jpg",
    twitterHandle: "@akevents_deli",
    locale: "en_IN",
    type: "website"
  };
  